name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest version of stable rust
      run: rustup update stable
    - name: Check formatting with cargofmt
      run: cargo fmt -- --check
    - name: Check for lint warnings
      run: cargo clippy --all-features -- -D warnings
  release-tests-ubuntu
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --tests
      - name: Run tests in release ed25519
        run: cargo test --all --release --features "ed25519" --tests
      - name: Run tests in release secp256k1
        run: cargo test --all --release --features "secp256k1" --tests
      - name: Run tests in release rust-secp256k1
        run: cargo test --all --release --features "rust-secp256k1" --tests
      - name: Run tests in release libp2p
        run: cargo test --all --release --features "libp2p" --tests
      - name: Run tests in release libp2p, rust-secp256k1
        run: cargo test --all --release --features "libp2p,rust-secp256k1" --tests
      - name: Run tests in release all features
        run: cargo test --all --release --all-features
  cargo-audit:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Get latest cargo audit
        run: cargo install --force cargo-audit
      - name: Run cargo audit to identify known security vulnerabilities reported to the RustSec Advisory Database
        run: cargo audit
  check-rustdoc-links:
    name: Check rustdoc intra-doc links
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2
    - name: Check rustdoc links
      run: RUSTDOCFLAGS="--deny broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items
